name: Build Katello API docs

on:
  push:
    branches:
      - katello-5.0-apidoc-build
  workflow_dispatch:

jobs:
  katello:
    uses: ogajduse/actions/.github/workflows/foreman_plugin.yml@apidoc-generation
    with:
      plugin: katello
      plugin_repository: ogajduse/katello
      plugin_version: katello-5.0-apidoc-build
      foreman_version: 5.0-stable
      test_existing_database: false
      test_core_tests: false
      additional_packages: libcap-dev
      generate_apidoc: true
